apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thousandeyesagent.fullname" . }}
  labels:
    {{- include "thousandeyesagent.labels" . | nindent 4 }}
data:
  TEAGENT_ACCOUNT_TOKEN: {{ required "A valid .Values.account_token is required!" .Values.account_token }} 
