{{- if not .Values.host_networking_mode.enabled}}
{{- if .Values.allow_outside_initiated_traffic.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thousandeyesagent.fullname" . }}
  labels:
    {{- include "thousandeyesagent.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "thousandeyesagent.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.allow_outside_initiated_traffic.port }}
      targetPort: {{ .Values.allow_outside_initiated_traffic.port }}
      nodePort: {{ .Values.allow_outside_initiated_traffic.port }}
{{- end }}
{{- end }}
